### ISSUE TITLE
running test data

### ISSUE THREAD

**Issue by HannahBenisty** [epi2me-labs/wf-16s#1]
### Ask away!

Hi! I have been trying to run a test with the test data but I get this error message:

Input path test_data does not exist.

 -- Check script '/Users/hbenisty/.nextflow/assets/epi2me-labs/wf-16s/./lib/fastqingress.nf' at line: 284 or see '.nextflow.log' file for more details

Do you have any suggestion?

Many thanks

**Comment by SamStudio8** [comment]
Hi @HannahBenisty, to help us to diagnose this issue, please can you open a "Bug report" type issue, and fill in the required information.
