### ISSUE TITLE
Support for database stored on a network drive

### ISSUE THREAD

**Issue by nikelau** [epi2me-labs/wf-16s#14]
### Is your feature related to a problem?

No

### Describe the solution you'd like

I have been trying to use the kraken2 nt database (> 500GB) for my pipeline and it seems that the workflow currently does not support the file being stored in a network location although it has already been mapped in Windows. 

### Describe alternatives you've considered

Is there a way that I can use the network folder directly?

**Comment by cjw85** [comment]
Hi @nikelau,

Please reopen an issue using the bug issue template and provide the information requested as doing so really helps us to help you.
