### ISSUE TITLE
How to pull a previous version of the workflow? 

### ISSUE THREAD

**Issue by irc47** [epi2me-labs/wf-16s#19]
### Ask away!

Hi All, 
I am looking to run a previous version of the workflow for reproducibility. Can anyone provide guidance on how to pull a specific version with nextflow? 
Thank you!

**Comment by julibeg** [comment]
Hi @irc47, on the command line, you can add `-r vX.Y.Z` to your command.

For instance, the `wf-16s` example command would then be

```
nextflow run epi2me-labs/wf-16s \ 
    --fastq 'wf-16s-demo/test_data' \ 
    --minimap2_by_reference \
    -r v1.1.3
```

for version 1.1.3.

In the EPI2ME Desktop Application, you can click the "Switch revision" button in the workflow's Overview page to choose a different version.

**Comment by irc47** [comment]
Thank you!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Julian Libiseller-Egger ***@***.***>
Sent: Tuesday, June 11, 2024 5:20:51 AM
To: epi2me-labs/wf-16s ***@***.***>
Cc: Ilana Cohen ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [epi2me-labs/wf-16s] How to pull a previous version of the workflow? (Issue #19)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


Hi @irc47<https://github.com/irc47>, on the command line, you can add -r vX.Y.Z to your command.

For instance, the wf-16s example command would then be

nextflow run epi2me-labs/wf-16s \
    --fastq 'wf-16s-demo/test_data' \
    --minimap2_by_reference \
    -r v1.1.3


for version 1.1.3.

In the EPI2ME Desktop Application, you can click the "Switch revision" button in the workflow's Overview page to choose a different version.
