### ISSUE TITLE
Direct additional report tables to output directory

### ISSUE THREAD

**Issue by aliciamrich** [epi2me-labs/wf-16s#20]
### Is your feature related to a problem?

It can be tedious to individually export and rename table formats only available through the HTML report, especially the optional tables for each sample that provide mapping coverage with each taxonomic ID and NCBI accession. I'd like something less tedious to incorporate into my pipeline with automatic redirection and naming of those csv/tsv files into my output directory.

### Describe the solution you'd like

I'm looking for more customization options to direct some of the data found in the html report into csv or tsv files in my output directory so that I can more easily read these data into R and manipulate them for custom analyses.

### Describe alternatives you've considered

Right now, I manually download the tables from the HTML file for each sample and then rename those files by sampleID. I wrote a function loop in R that uses dplyr to read these tables into R, add a column for sampleID based on the file basename, and merge them into a single data frame that I can more easily manipulate with as much of the classification information as possible in a single object.

**Comment by nggvs** [comment]
Hi @aliciamrich ,

Thank you for your feedback and for using the workflow! We'll take into account for future releases.

**Comment by nggvs** [comment]
I have noted this as a possible additional feature so I'll close the issue meanwhile is processed.
Thank you very  much for using the workflow!
