### ISSUE TITLE
How to obtain a phylogenic tree

### ISSUE THREAD

**Issue by CamillePhilippeSCI** [epi2me-labs/wf-16s#22]
### Ask away!

Hello, 
I am willing to do Faiths phyolgeny test in R but in my outputs after EPI2ME 16s WF i have the taxonomic table and no phyloseq object. 
Could someone please tell me if it would be possible to create a phylogenic tree using this workflow ? 
Thankyou

**Comment by nggvs** [comment]
Hi @CamillePhilippeSCI ,
the wf doesn't create a phylogenic tree directly. You'd need to look into phyloseq input files/formats and write your own script for it
Thank you very much for using the workflow!

**Comment by CamillePhilippeSCI** [comment]
Hi,

Thanks for your answer !
So you think that i can add lines in the WF to create it or do i have to start all over with a new script and the raw data ?

**Comment by nggvs** [comment]
Hi @CamillePhilippeSCI ,
If you want to add some lines to the wf, is fine, but then is going to be more difficult to update it (except if you feel comfortable using git). If not, I'd suggest to write a different script that reads the output directory (there is a copy of the abundance table there)

**Comment by DBrache** [comment]
I am also trying to make a phylogenetic for 16S ONT.  Are there outputs in the workflow that generate a representative OTU table and a sequence table so I can create a tree?
