### ISSUE TITLE
Instead of taxonomic assignment to "Unknown", classifying to the next highest taxonomic level

### ISSUE THREAD

**Issue by el3rin** [epi2me-labs/wf-16s#23]
Hi! 
I'm using the 16S-wf in the Epi2Me desktop application. I typically have full 16S reads and use the NCBI database that is provided in the workflow and minimap2 to assign taxonomy at species level.
I understand that "Unknown" reads in the final abundance table come from if the query coverage for a read is lower than what was set up in the workflow. In my case this is 90%. Please correct me if I'm wrong.
Is it possible to still assign taxonomy to these Unknowns but at higher taxonomic level, e.g., if I use to assign at species level, it would try to do it at genus level? 
Perhaps there's already some documentation I've missed that would allow me to extract these Unknowns and "feed" them through the workflow again using genus as the highest assignment level and then combine the two abundance tables? 
I'm not that savvy in the command line, but I can follow tutorials/examples and make small edits to fit it to my data.
Thanks, and cheers!

**Comment by nggvs** [comment]
Hi @el3rin ,

Let me make sure that I'm understanding your question. The pipeline moves to unclassified/unknow those sequences that are below a threshold of identity of coverage as you have indicated (although just in the results, it doesn't modify the BAM files resulting from the alignment). Those sequences are not reassigned to a different level in the same run (you can run the workflow using genus level, but then all the sequences would be classified at the genus level).

However, there is a tutorial about how to recover the unclassified sequences or any sequence from the minimap2 or kraken2 outputs: https://labs.epi2me.io/post-meta-analysis/ Hope you find it useful!

Thank you for using the workflow!

**Comment by el3rin** [comment]
Awesome, thanks! Totally missed that there.
And yes, I want to pull those unclassified reads and feed them through the classifier again, but at higher taxonomic assignment.
Would be handy if this could be more automated, although I don't know how 'easy' it would be to even automate.
What I mean is that the workflow has an option to extract the unclassified reads automatically into the results folder.

Cheers and thanks again!

**Comment by nggvs** [comment]
Hi @el3rin,
I have taken noted on this to consider adding it in future releases: would be nice for you if there is an option to output the unclassified reads so you can feed the workflow with them at maybe run the analysis at a different taxonomic level?
Thank you very much for using the workflow!

**Comment by nggvs** [comment]
Hi @el3rin ,
As I have reported this internally, I'll close the issue meanwhile.
I hope you can see it in future versions of the pipeline!
