### ISSUE TITLE
No "species" level information in the "Lineages" section 

### ISSUE THREAD

**Issue by drabitoris** [epi2me-labs/wf-16s#24]
### Ask away!

Hi team,

I've run the v1.2.0 and I noticed (see below the screenshot) in the html report there is no species level info even I've chosen "species" for the "select rank". I wonder if this pipeline supports species-level classification?
![Screenshot 2024-08-02 at 11 25 57 am](https://github.com/user-attachments/assets/f200d8ba-34de-4eea-9fdc-5d8791198a47)

**Comment by drabitoris** [comment]
I noticed that if based on kraken2 then I can set the taxonomic_rank parameter to S for species-level classification. Does the minimap2 pipeline also support this since it would be good to have a finer resolution?

**Comment by nggvs** [comment]
Hi @drabitoris ,
You should be able to view species level in the report except when using the SILVA database. Could you provide more info about how you are running the workflow (like if you are using a custom database for example). Also you're not observing species just in the sankey plot or in the rest of the report?

Thank you very much in advance!

**Comment by nggvs** [comment]
Hi @drabitoris ,
Is there any news on this? In both pipelines you should be able to use the species level, except for the SILVA database.
Thank you very much for using the workflow!

**Comment by drabitoris** [comment]
Yes. Made it down to species level via both classifiers. Thank you! ☺️

**Comment by nggvs** [comment]
Nice to hear that! I'll close the issue now that problem has been resolved.
Thank you very much for using the workflow!
