### ISSUE TITLE
Ways to improve minimap classification?

### ISSUE THREAD

**Issue by osvatic** [epi2me-labs/wf-16s#28]
### Ask away!

I am currently trying to use minimap on a ONT dataset to get a finer resolution, ideally down to species, on some full length amplicons. 
When I run this dataset using kraken as the classifier (with any database) I get a high percentage of the reads classified to some degree. When I run it with minimap I end up with ~99% unclassified regardless of dataset. 

Are there settings that could be tweaked to adjust this?   Maybe min_percent_identity?

**Comment by nggvs** [comment]
Hi @osvatic ,
Thank you very much for using the workflow!
You can update to the latest version1.3.0. There is a new table that shows the unmapped sequences and there is also the number of unclassified in the rest of plots. Hopefully, this may give you an idea on how the [min_percent_identity and min_ref_coverage](https://github.com/epi2me-labs/wf-16s?tab=readme-ov-file#minimap2-options) are working and you can decrease this value if you consider it appropriate. To use the species level, you can change the [taxonomic resolution](https://github.com/epi2me-labs/wf-16s?tab=readme-ov-file#reference-options) to "S" (except in the SILVA database).
Hope you find this useful!

**Comment by nggvs** [comment]
Hi @osvatic ,
Are you still experiencing this issue? 
Thank you very much in advance!

**Comment by osvatic** [comment]
No, I was able to use the options to try and adjust the settings to improve the results.
