### ISSUE TITLE
BAM files in the no_host_bam folder

### ISSUE THREAD

**Issue by sachiwije** [epi2me-labs/wf-16s#29]
### Ask away!

Hi,
How can the reads in the BAM files in the "no_host_bam" folder be described?

1. Not mapped to host  + removed too short and too-long reads
2. Only Not mapped to the host

Thank you! :)

**Comment by nggvs** [comment]
Hi!
There is a first step to exclude reads based on the minimum and maximum read length.
Host depletion occurs after that, the no_host_bam includes the reads that have passed the min/max filters and that have not mapped in the host reference, which are the ones that continue the rest of the analysis
