### ISSUE TITLE
Report format

### ISSUE THREAD

**Issue by llk578496** [epi2me-labs/wf-16s#3]
Hi @mattdmem ,

Thank you for creating `wf-16s`. As this succeeds `Epi2me FASTQ 16S`, could `wf-16s` generate reports matching `Epi2me's` format?

Producing an `Epi2me-style` report would be appreciated to integrate smoothly into our existing downstream processes. Please advise if this is possible or provide examples of specifications needed.

We're eager to use `wf-16s` advances while allowing continuity. Thank you for your time.

Regards,
Eddie

**Comment by mattdmem** [comment]
Hi @llk578496,

Thanks for your interest in the workflow. What is it about the old EPI2ME reports that you need that the new ones don't provide? Unfortunately we aren't going to be providing legacy style reports, but we can consider adding features to the new ones.

Matt

**Comment by llk578496** [comment]
We would like to request for adding barcode filtering to the `wf-16s` abundance section. In `Epi2me`, we could filter abundances by sample. This allowed individual reports like below. 
![Epi2me-16s-abundance](https://github.com/epi2me-labs/wf-16s/assets/78581211/0415cb9c-84ac-4ce4-a1c5-b37cd63fa47d)

However, `wf-16s` currently combines abundances across all samples in a batch. 
![wf-16s-abundance](https://github.com/epi2me-labs/wf-16s/assets/78581211/9fe2609c-0878-45d0-b791-ef5596630bf7)

Barcode filtering in `wf-16s` would restore our ability to examine taxa distributions at the sample level.
Thank you for any help on this request.

**Comment by mattdmem** [comment]
@nggvs is going to add a parameter to adjust abundance thresholds per sample - will that be helpful?

**Comment by nggvs** [comment]
Hi @llk578496 ,
Are you still interested in having this feature?

**Comment by llk578496** [comment]
Hi @nggvs ,

Sure! We will be grateful if you could add this feature. 

Adding barcode filtering and individual csv export with taxa sorted by abundance would be great for the reporting. Also, It will be great if these csv could be exported by default.

Thanks you very much!

**Comment by nggvs** [comment]
Hi @llk578496 ,
I take note on this and will consider this option for future releases. Just to make sure this is what you are interested in:
- Individual CSVs (better if they are also in the output directory) for each sample sorted by abundances
I'm not sure of what you would like as barcode filtering? Could you explain that with more detail?

Thank you for using the pipeline!

**Comment by llk578496** [comment]
Being able to filter results and see abundances by individual barcode which similar to the handy filter in Lineages would be ideal.

Thank a lot!

![Screenshot from 2024-03-02 09-28-03](https://github.com/epi2me-labs/wf-16s/assets/78581211/a5766f63-0a0a-414c-b8fc-255ba27f0975)

**Comment by nggvs** [comment]
Hi @llk578496 ,
First of all thank you for your suggestions, I agree that it would make the report more convenient for some specific cases. We may provide single sample reports apart from a general one. Nevertheless I think that unfortunately is not going to be implement in the short term. However, I'll take this into account as a future feature request! Please keep making suggestions so that we can improve our workflows!
